SET DEFINE OFF
INSERT INTO ADMINS (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) 
VALUES (10, 'Altynay', 'Turzhanova', 'aturzhanova@gmail.com', 'hardcore');
INSERT INTO ADMINS (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) 
VALUES (11, 'Aruzhan', 'Serikbaeva', 'aserikbayeva@gmail.com', 'purple');
INSERT INTO ADMINS (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) 
VALUES (12, 'Zhanel', 'Oralova', 'zoralova@gmail.com', 'banana');
INSERT INTO ADMINS (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) 
VALUES (13, 'Farukh', 'Iskalinov', 'fiskalinov@gmail.com', 'junior');
INSERT INTO ADMINS (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) 
VALUES (14, 'Assem', 'Talasbek', 'atalasbek@gmail.com', 'hannah');
INSERT INTO ADMINS (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) 
VALUES (15, 'Aisultan', 'Shoynbek', 'ashoiynbek@gmail.com', 'porsche');
INSERT INTO ADMINS (ADMIN_ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) 
VALUES (16, 'Asya', 'Dyisenova', 'adiusenova@gmail.com', 'lakers');
-- Import Data into table ADMINS from file admins.xlsx . Task successful and sent to worksheet.

SET DEFINE OFF
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10001, 'Marat', 'Daniyarbekov', 'Uralsk', 77055558182, 'mdaniyarbekov@gmail.com', '123456', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10002, 'Madi', 'Ardagerev', 'Nur-sultan', 77025557094, 'mardagerev@gmail.com', 'password', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10003, 'Ardager', 'Yerzhanev', 'Qostanay', 77775552182, 'ayerzhanaev@gmail.com', '12345678', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10004, 'Beibitzhan', 'Temirzhanov', 'Aktau', 77055556004, 'btemirzhanov@gmail.com', 'qwerty', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10005, 'Serik', 'Daniyarev', 'Turkestan', 77055553356, 'sdaniyarev@gmail.com', '123456789', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10006, 'Nurbek', 'Madiyarev', 'Aktobe', 77015553945, 'nmadiyarev@gmail.com', '12345', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10007, 'Medet', 'Camranev', 'Kokshetau', 77015559377, 'mcamranev@gmail.com', '1234', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10008, 'Akhmet', 'Bakhytzhanov', 'Taraz', 77025551723, 'abakhytzhanov@gmail.com', '111111', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10009, 'Adil', 'Madiev', 'Nur-sultan', 77055556991, 'amadiev@gmail.com', '1234567', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10010, 'Yerzhan', 'Bekbolatev', 'Uralsk', 77055558182, 'ybekbolataev@gmail.com', 'dragon', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10011, 'Elena', 'Abdulayeva', 'Qaragandy', 77025557094, 'eabdualiyeva@gmail.com', '123123', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10012, 'Sergey', 'Abdulin', 'Aqtobe', 77775552182, 'sabdulin@gmail.com', 'baseball', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10013, 'Tatyana', 'Abdullayeva', 'taraz', 77055556004, 'tabdullayeva@gmail.com', 'abc123', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10014, 'Natalya', 'Abdulova', 'Shymkent', 77055553356, 'nabdulova@gmail.com', 'football', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10015, 'Alexander', 'Aitmukhambetov', 'Nur-sultan', 77015553945, 'aaitmukhambetov@gmail.com', 'monkey', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10016, 'Vladimir', 'Akhmetov', 'Semey', 77015559377, 'vakhmetov@gmail.com', 'letmein', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10017, 'Olga', 'Aliyeva', 'Almaty', 77025551723, 'oaliyeva@gmail.com', '696969', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10018, 'Ruslan', 'Aronov', 'Shymkent', 77055556991, 'raronov@gmail.com', 'shadow', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10019, 'Andrey', 'Bayzhanov', 'Qostanay', 77055558182, 'abauyrzhanov@gmail.com', 'master', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10020, 'Irina', 'Ibragimova', 'Uralsk', 77025557094, 'iibragimova@gmail.com', '666666', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10021, 'Svetlana', 'Iskakova', 'Shymkent', 77775552182, 'siskakova@gmail.com', 'qwertyuiop', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10022, 'Aleksandr', 'Karimov', 'Nur-sultan', 77055556004, 'akarimov@gmail.com', '123321', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10023, 'Aygerim', 'Karimova', 'Uralsk', 77055553356, 'akarimova@gmail.com', 'mustang', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10024, 'Nadezhda', 'Kedryuk', 'Aqtobe', 77015553945, 'nkedryuk@gmail.com', '1234567890', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10025, 'Azamat', 'Nabiyev', 'Qyzylorda', 77015559377, 'anabiyev@gmail.com', 'michael', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10026, 'Marina', 'Nazarbayeva', 'Pavlodar', 77025551723, 'mnazarbayeva@gmail.com', '654321', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10027, 'Dinara', 'Niyazova', 'Ust-kamenogorsk', 77055556991, 'dniyazova@gmail.com', 'pussy', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10028, 'Viktor', 'Niyazov', 'Qyzylorda', 77055558182, 'vniyazov@gmail.com', 'superman', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10029, 'Talgat', 'Qasymbek', 'Ust-kamenogorsk', 77025557094, 'tqasymbek@gmail.com', '1qaz2wsx', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10030, 'Serik', 'Sadykov', 'Aqtau', 77775552182, 'ssadykov@gmail.com', '7777777', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10031, 'Madina', 'Tagaeva', 'Aqtay', 77055556004, 'mtagayeva@gmail.com', 'fuckyou', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10032, 'Galina', 'Tynyshbaeva', 'Qostanay', 77055553356, 'gtynyshbaeva@gmail.com', '121212', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10033, 'Nursultan', 'Usenov', 'Qyzylorda', 77015553945, 'nusenov@gmail.com', '0', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10034, 'Nikolay', 'Zhakiyanov', 'Uralsk', 77015559377, 'nzhakiyarov@gmail.com', 'qazwsx', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10035, 'Lyudmila', 'Zhaparova', 'Nur-sultan', 77025551723, 'lzhaparova@gmail.com', '123qwe', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10036, 'Denis', 'Kenes', 'Semey', 77055556991, 'dkenes@gmail.com', 'killer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10037, 'Erzhan', 'Omarov', 'Nur-sultan', 77055558182, 'eomarov@gmail.com', 'trustno1', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10038, 'Akmaral', 'Sultanova', 'Nur-sultan', 77025557094, 'asultanova@gmail.com', 'jordan', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10039, 'Arman', 'Aliev', 'Nur-sultan', 77775552182, 'aaliev@gmail.com', 'jennifer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10040, 'Asel', 'Barat', 'Shymkent', 77055556004, 'abarat@gmail.com', 'zxcvbnm', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10041, 'Valentina', 'Akhmetova', 'Karagandy', 77055553356, 'vakhmetova@gmail.com', 'asdfgh', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10042, 'Anna', 'Umarova', 'Almaty', 77015553945, 'aumarova@gmail.com', 'hunter', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10043, 'Timur', 'Belgibaev', 'Nur-sultan', 77015559377, 'tbelgibaev@gmail.com', 'buster', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10044, 'Ivan', 'Akhmetov', 'Karagandy', 77025551723, 'iakhmetov@gmail.com', 'soccer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10045, 'Alexey', 'Kemelov', 'Shymkent', 77055556991, 'akemelov@gmail.com', 'harley', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10046, 'Ekaterina', 'Bolatbek', 'Nur-sultan', 77055558182, 'ebolatbek@gmail.com', 'batman', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10047, 'Nurlan', 'Ivanov', 'Shymkent', 77025557094, 'nivanov@gmail.com', 'andrew', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10048, 'Aydana', 'Ivanova', 'Karagandy', 77775552182, 'aivanova@gmail.com', 'tigger', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10049, 'Igor', 'Kambarov', 'Almaty', 77055556004, 'ikambarov@gmail.com', 'sunshine', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10050, 'Marat', 'Iskakov', 'Nur-sultan', 77055553356, 'miskakov@gmail.com', 'iloveyou', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10051, 'Diana', 'Boyko', 'Karagandy', 77015553945, 'dboyko@gmail.com', 'fuckme', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10052, 'Erlan', 'Smagulov', 'Shymkent', 77015559377, 'esmagulov@gmail.com', '2000', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10053, 'Kanat', 'Aliev', 'Shymkent', 77025551723, 'kaliev@gmail.com', 'charlie', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10054, 'Kuanysh', 'Omarov', 'Atyrau', 77055556991, 'komarov@gmail.com', 'robert', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10055, 'Oleg', 'Ospanov', 'Ust-kamenogorsk', 77055558182, 'oospanov@gmail.com', 'thomas', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10056, 'Bakhytzhan', 'Smagulov', 'Petropavlovsk', 77025557094, 'bsmagulov@gmail.com', 'hockey', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10057, 'Nurzhan', 'Ospanov', 'Uralsk', 77775552182, 'nospanov@gmail.com', 'ranger', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10058, 'Evgeny', 'Serikov', 'Qyzylorda', 77055556004, 'eserikov@gmail.com', 'daniel', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10059, 'Gulmira', 'Tsoy', 'Nur-sultan', 77055553356, 'gtsoy@gmail.com', 'starwars', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10060, 'Lyubov', 'Suleymenova', 'Uralsk', 77015553945, 'lsuleymenova@gmail.com', 'klaster', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10061, 'Dauren', 'Karimov', 'Nur-sultan', 77015559377, 'dkarimov@gmail.com', '112233', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10062, 'Orken', 'Ibragimov', 'Qyzylorda', 77025551723, 'oibragimov@gmail.com', 'george', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10063, 'Anastasia', 'Bondarenko', 'Nur-sultan', 77055556991, 'abondarenko@gmail.com', 'asshole', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10064, 'Dmitry', 'Eleusiz', 'Qyzylorda', 77055558182, 'deleusiz@gmail.com', 'computer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10065, 'Pavel', 'Asanov', 'Shymkent', 77025557094, 'pasanov@gmail.com', 'michelle', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10066, 'Askar', 'Petrov', 'Aqtobe', 77775552182, 'apetrov@gmail.com', 'jessica', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10067, 'Saltanat', 'Kalieva', 'Nur-sultan', 77055556004, 'skalieva@gmail.com', 'pepper', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10068, 'Daulet', 'Nigmashev', 'Aqtau', 77055553356, 'dnigmashev@gmail.com', '1111', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10069, 'Murat', 'Shevchenko', 'Aqtau', 77015553945, 'mshevchenko@gmail.com', 'zxcvbn', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10070, 'Alina', 'Popova', 'Atyrau', 77015559377, 'apopova@gmail.com', '555555', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10071, 'Darkhan', 'Valiev', 'Uralsk', 77025551723, 'dvaliev@gmail.com', '11111111', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10072, 'Bauyrzhan', 'Suleymenov', 'Qyzylorda', 77055556991, 'bsuleymenov@gmail.com', '131313', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10073, 'Inkar', 'Muratova', 'Atyrau', 77055558182, 'imuratova@gmail.com', 'freedom', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10074, 'Ertugan', 'Romanyuk', 'Aqtobe', 77025557094, 'eromanyuk@gmail.com', '777777', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10075, 'Aida', 'Asanova', 'Petropavlovsk', 77775552182, 'aasanova@gmail.com', 'pass', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10076, 'Rustam', 'Ibraev', 'Semey', 77055556004, 'ribraev@gmail.com', 'fuck', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10077, 'Kristina', 'Zhumabaeva', 'Uralsk', 77055553356, 'kzhumabaeva@gmail.com', 'maggie', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10078, 'Olzhas', 'Ibraev', 'Uralsk', 77015553945, 'oibraev@gmail.com', '159753', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10079, 'Mikhail', 'Ismailov', 'Qaragandy', 77015559377, 'mismailov@gmail.com', 'aaaaaa', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10080, 'Aygul', 'Kovalenko', 'Nur-sultan', 77025551723, 'akovalenko@gmail.com', 'ginger', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10081, 'Zhandos', 'Sarbalin', 'Atyrau', 77055556991, 'zsarbalin@gmail.com', 'princess', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10082, 'Damir', 'Tulegenov', 'Ust-kamenogorsk', 77055558182, 'dtulegenov@gmail.com', 'joshua', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10083, 'Yulia', 'Iskakova', 'Petropavlovsk', 77025557094, 'yiskakova@gmail.com', 'cheese', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10084, 'Alibek', 'Popov', 'Ust-kamenogorsk', 77775552182, 'apopov@gmail.com', 'amanda', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10085, 'Daniar', 'Musin', 'Aqtau', 77055556004, 'amusin@gmail.com', 'summer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10086, 'Samat', 'Mamedov', 'Qostanay', 77055553356, 'amamedov@gmail.com', 'love', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10087, 'Dana', 'Abdullaeva', 'Nur-sultan', 77015553945, 'dabdullaeva@gmail.com', 'ashley', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10088, 'Evgeniy', 'Sadyk', 'Atyrau', 77015559377, 'esadyk@gmail.com', '6969', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10089, 'Alisher', 'Muratov', 'Aqsai', 77025551723, 'amuratov@gmail.com', 'nicole', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10090, 'Roman', 'Aubakirov', 'Shymkent', 77055556991, 'raubakirov@gmail.com', 'chelsea', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10091, 'Anastasiya', 'Kuznetsova', 'Pavlodar', 77055558182, 'akuznetsova@gmail.com', 'biteme', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10092, 'Erbol', 'Musaev', 'Petropavlovsk', 77025557094, 'emusaev@gmail.com', 'matthew', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10093, 'Aleksey', 'Nurdulla', 'Uralsk', 77775552182, 'anurdulla@gmail.com', 'access', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10094, 'Akerke', 'Ibragimova', 'Uralsk', 77055556004, 'aibragimova@gmail.com', 'yankees', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10095, 'Zarina', 'Amangeldi', 'Ust-kamenogorsk', 77055553356, 'zamangeldi@gmail.com', '987654321', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10096, 'Moldir', 'Kusainova', 'Atyrau', 77015553945, 'mkusainova@gmail.com', 'dallas', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10097, 'Mariya', 'Sultanova', 'Semey', 77015559377, 'msultanova@gmail.com', 'austin', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10098, 'Dmitriy', 'Kudarov', 'Aqtobe', 77025551723, 'dkudarov@gmail.com', 'thunder', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10099, 'Maxim', 'Nauryzbaev', 'Taraz', 77055556991, 'mnauryzbaev@gmail.com', 'taylor', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10100, 'Nina', 'Apsalyamova', 'Qyzylorda', 77055558182, 'napsalymova@gmail.com', 'matrix', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10101, 'Sultan', 'Kaliev', 'Almaty', 77025557094, 'skaliev@gmail.com', 'william', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10102, 'Dias', 'Nurgaliev', 'Semey', 77775552182, 'dnurgaliev@gmail.com', 'corvette', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10103, 'Yuliya', 'Bazarbaeva', 'Aqtau', 77055556004, 'ybazarbaeva@gmail.com', 'hello', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10104, 'Rustem', 'Mukashev', 'Petropavlovsk', 77055553356, 'rmukashev@gmail.com', 'martin', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10105, 'Ayzhan', 'Isaeva', 'Nur-sultan', 77015553945, 'aisaeva@gmail.com', 'heather', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10106, 'Larisa', 'Zhumagalieva', 'Aqtau', 77015559377, 'lzhumagalieva@gmail.com', 'secret', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10107, 'Dima', 'Amangeldy', 'Nur-sultan', 77025551723, 'damangeldy@gmail.com', 'fucker', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10108, 'Zhanna', 'Tulegenova', 'Nur-sultan', 77055556991, 'ztulegenova@gmail.com', 'merlin', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10109, 'Nikita', 'Bisenov', 'Qaragandy', 77055558182, 'nbisenov@gmail.com', 'diamond', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10110, 'Daniyar', 'Galiev', 'Shymkent', 77025557094, 'dgaliev@gmail.com', '1234qwer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10111, 'Anton', 'Sadykov', 'Ust-kamenogorsk', 77775552182, 'asadykov@gmail.com', 'gfhjkm', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10112, 'Azat', 'Sauytbay', 'Taldyqorgan', 77055556004, 'asauytbay@gmail.com', 'hammer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10113, 'Zhasulan', 'Sharipov', 'Aqtobe', 77055553356, 'zsharipov@gmail.com', 'silver', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10114, 'Aybek', 'Sarsenbaev', 'Aqtobe', 77015553945, 'asarsenbaev@gmail.com', '222222', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10115, 'Zhansaya', 'Shaymerdenova', 'Qyzylorda', 77015559377, 'zshaymerdenova@gmail.com', '88888888', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10116, 'Aliya', 'Amangeldieva', 'Uralsk', 77025551723, 'aamangeldieva@gmail.com', 'anthony', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10117, 'Almas', 'Mamirov', 'Aqtobe', 77055556991, 'amamirov@gmail.com', 'justin', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10118, 'Maxat', 'Petrov', 'Aqtobe', 77055558182, 'mpetrov@gmail.com', 'test', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10119, 'Berik', 'Beshirov', 'Shymkent', 77025557094, 'bbeshirov@gmail.com', 'bailey', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10120, 'Asem', 'Amanzholova', 'Taraz', 77775552182, 'aamanzholova@gmail.com', 'q1w2e3r4t5', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10121, 'Gulnar', 'Zhumabaeva', 'Qostanay', 77055556004, 'gzhumabaeva@gmail.com', 'patrick', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10122, 'Erkebulan', 'Serikbaev', 'Aqtau', 77055553356, 'eserikbaev@gmail.com', 'internet', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10123, 'Vera', 'Askarova', 'Atyrau', 77015553945, 'vaskarova@gmail.com', 'scooter', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10124, 'Saule', 'Mukanova', 'Aqtobe', 77015559377, 'smukanova@gmail.com', 'orange', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10125, 'Nurdaulet', 'Yusupov', 'Aqsay', 77025551723, 'nyusupov@gmail.com', '11111', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10126, 'Askhat', 'Karimov', 'Taraz', 77055556991, 'akarimov@gmail.com', 'golfer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10127, 'Aslan', 'Ramazanov', 'Qostanay', 77055558182, 'aramazanov@gmail.com', 'cookie', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10128, 'Kayrat', 'Syzdykov', 'Qaragandy', 77025557094, 'ksyzdykov@gmail.com', 'richard', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10129, 'Nazerke', 'Chebotar', 'Semey', 77775552182, 'nchebotar@gmail.com', 'samantha', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10130, 'Aynura', 'Abuova', 'Petropavlovsk', 77055556004, 'aabuova@gmail.com', 'bigdog', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10131, 'Meruert', 'Saparova', 'Petropavlovsk', 77055553356, 'msaparova@gmail.com', 'guitar', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10132, 'Viktoria', 'Abdrakhmanova', 'Nur-sultan', 77015553945, 'vabdrakhmanova@gmail.com', 'jackson', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10133, 'Ilya', 'Ilyasov', 'Atyrau', 77015559377, 'iilyasov@gmail.com', 'whatever', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10134, 'Konstantin', 'Shnayder', 'Nur-sultan', 77025551723, 'kshnayder@gmail.com', 'mickey', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10135, 'Zhanar', 'Aymusheva', 'Petropavlovsk', 77055556991, 'zaymusheva@gmail.com', 'chicken', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10136, 'Vlad', 'Bekenov', 'Shymkent', 77055558182, 'vbekenov@gmail.com', 'sparky', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10137, 'Aidana', 'Parasyukova', 'Shymkent', 77025557094, 'aparasyukova@gmail.com', 'snoopy', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10138, 'Aynur', 'Kuanysheva', 'Aqtobe', 77775552182, 'akuanysheva@gmail.com', 'maverick', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10139, 'Adil', 'Aubakirov', 'Petropavlovsk', 77055556004, 'aaubakirov@gmail.com', 'phoenix', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10140, 'Vadim', 'Rakhmetov', 'Semey', 77055553356, 'vrakhmetov@gmail.com', 'camaro', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10141, 'Zhuldyz', 'Goncharova', 'Aqtobe', 77015553945, 'zgoncharova@gmail.com', 'sexy', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10142, 'Elmira', 'Khanova', 'Qostanay', 77015559377, 'ekhanova@gmail.com', 'peanut', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10143, 'Arystanbek', 'Zhaikbaev', 'Ust-kamenogorsk', 77025551723, 'azhaikbaev@gmail.com', 'morgan', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10144, 'Karina', 'Askarova', 'Shymkent', 77055556991, 'kaskarova@gmail.com', 'welcome', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10145, 'Bekzat', 'Morozov', 'Petropavlovsk', 77055558182, 'bmorozov@gmail.com', 'falcon', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10146, 'Aigerim', 'Isaeva', 'Aqtau', 77025557094, 'aaisaeva@gmail.com', 'cowboy', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10147, 'Nurbek', 'Zhumadilov', 'Semey', 77775552182, 'nzhumadilov@gmail.com', 'ferrari', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10148, 'Indira', 'Esimkhanova', 'Shymkent', 77055556004, 'iesimkhanova@gmail.com', 'samsung', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10149, 'Rekhimzhan', 'Syzdykov', 'Ust-kamenogorsk', 77055553356, 'rsyzdykov@gmail.com', 'andrea', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10150, 'Laura', 'Kuznetsova', 'Petropavlovsk', 77015553945, 'lkuznetsova@gmail.com', 'smokey', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10151, 'Aydos', 'Orazbaev', 'Ust-kamenogorsk', 77015559377, 'aorazbaev@gmail.com', 'steelers', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10152, 'Abzal', 'Nazarova', 'Qaragandy', 77025551723, 'anazarova@gmail.com', 'joseph', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10153, 'Gaukhar', 'Utegenova', 'Taraz', 77055556991, 'gutegenova@gmail.com', 'mercedes', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10154, 'Marzhan', 'Kusainova', 'Kokshetau', 77055558182, 'makusainova@gmail.com', 'dakota', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10155, 'Maksim', 'Abdrakhmanov', 'Nur-sultan', 77025557094, 'mabdirakhmanov@gmail.com', 'arsenal', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10156, 'Dina', 'Ismailova', 'Pavlodar', 77775552182, 'dismailova@gmail.com', 'eagles', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10157, 'Aruzhan', 'Nurgalieva', 'Nur-sultan', 77055556004, 'anurgalieva@gmail.com', 'melissa', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10158, 'Viktoriya', 'Gumarova', 'Nur-sultan', 77055553356, 'vgumarova@gmail.com', 'boomer', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10159, 'Kamila', 'Sharipova', 'Shymkent', 77015553945, 'ksharipova@gmail.com', 'booboo', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10160, 'Alena', 'Shmidt', 'Pavlodar', 77015559377, 'ashmidt@gmail.com', 'spider', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10161, 'Oxana', 'Mukanova', 'Qaragandy', 77025551723, 'omukhanova@gmail.com', 'nascar', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10162, 'Duman', 'Utegenov', 'Pavlodar', 77055556991, 'dutegenov@gmail.com', 'monster', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10163, 'Altynay', 'Yusupova', 'Qostanay', 77055558182, 'ayusupova@gmail.com', 'tigers', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10164, 'Ali', 'Nazarenko', 'Pavlodar', 77025557094, 'anazarenko@gmail.com', 'yellow', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10165, 'Yuriy', 'Kurbanov', 'Atyrau', 77775552182, 'ykurbanov@gmail.com', 'xxxxxx', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10166, 'Darya', 'Levitskaya', 'Nur-sultan', 77055556004, 'dlevitskaya@gmail.com', '123123123', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10167, 'Gulnara', 'Volkova', 'Shymkent', 77055553356, 'gvolkova@gmail.com', 'gateway', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10168, 'Anatoliy', 'Tkachenko', 'Nur-sultan', 77015553945, 'atkachenko@gmail.com', 'marina', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10169, 'Kirill', 'Smirnov', 'Nur-sultan', 77015559377, 'ksmirnov@gmail.com', 'diablo', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10170, 'Araylym', 'Abenova', 'Aqtau', 77025551723, 'aabenova@gmail.com', 'bulldog', NULL);
INSERT INTO ECO_USERS (USER_UID, FIRST_NAME, LAST_NAME, CITY, CONTACT_NUMBER, EMAIL, PASSWORD, PROFILE_IMAGE) 
VALUES (10171, 'Dastan', 'Utegenov', 'Petropavlovsk', 77055556991, 'dautegenov@gmail.com', 'qwer1234', NULL);
-- Import Data into table ECO_USERS from file users (2).xlsx . Task successful and sent to worksheet.

SET DEFINE OFF
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (501, 'Чем отличаются экспресс-тест и ПЦР-тесты на COVID-19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 10);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (502, 'Чего нельзя делать перед сдачей ПЦР-теста?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 11);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (503, 'Что нужно делать во время сдачи ПЦР-теста?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 12);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (504, 'Сколько времени может уйти для получения результатов теста?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 13);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (505, 'Что делать, если у меня тест на Covid-19 дал положительный результат?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 14);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (506, 'Что делать, если тест подтвердил, что я заразился коронавирусом, но у меня нет никаких симптомов?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 15);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (507, 'Что такое COVID-19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 16);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (508, 'Question', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 10);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (509, 'Что делать пациентам с тяжелым течением заболевания?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 11);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (510, 'Кому угрожает риск тяжелого течения болезни?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 12);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (511, 'Имеются ли у COVID-19 долгосрочные последствия?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 13);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (512, 'Как защитить себя и других, если мы не знаем, кто заражен вирусом?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 14);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (513, 'В каких случаях необходимо пройти тестирование на COVID‑19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 15);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (514, 'Какой тест необходимо выполнить для подтверждения или исключения COVID-19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 16);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (515, 'Что такое экспресс-тесты?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 10);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (516, 'Какой тест позволяет уточнить факт ранее перенесенной COVID-19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 11);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (517, 'В чем разница между изоляцией и карантином?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 12);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (518, 'Что делать, если у меня были тесные контакты с человеком, инфицированным COVID-19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 13);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (519, 'Сколько времени проходит между заражением COVID-19 и возникновением симптомов?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 14);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (520, 'Существует ли вакцина, препарат или другой способ лечения COVID-19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 15);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (521, 'Что я должен делать, если у меня симптомы COVID-19, и в какой момент следует обратиться за медицинской помощью?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 16);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (522, 'Разработано ли лечение COVID-19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 10);
INSERT INTO FAQ (QUESTION_ID, QUESTION, ANSWER, ADMIN_ID) 
VALUES (523, 'Являются ли антибиотики эффективным средством профилактики или лечения COVID-19?', 'Экспресс-тесты позволяют выявить наличие антител к коронавирусу. Антитела говорят о том, что человек уже перенёс инфекцию. Экспресс-тест осуществляется забором крови из пальца или вены. Чтобы определить, есть ли инфекция в организме в данный момент, проводят ПЦР-тест. При этом берут мазок из носоглотки или из ротоглотки.', 11);
-- Import Data into table FAQ from file faq (1).xlsx . Task successful and sent to worksheet.


SET DEFINE OFF
INSERT INTO NEWS (TOPIC, THESIS, ADMIN_ID, NEWS_IMAGE) 
VALUES ('Wear a mask', 'Overview
DO

Wear masks to help protect yourself from getting or spreading COVID-19
Wear masks with two or more layers to stop the spread of COVID-19
Wear the mask over your nose and mouth and secure it under your chin
DO NOT

Put masks on someone two years and younger
Put masks on people who have trouble breathing, or people who cannot remove the mask without assistance
Wear masks intended for healthcare workers, for example, N95 respirators', 10, NULL);
INSERT INTO NEWS (TOPIC, THESIS, ADMIN_ID, NEWS_IMAGE) 
VALUES ('Who will get the Covid vaccine first?', 'Overview
DO

Wear masks to help protect yourself from getting or spreading COVID-19
Wear masks with two or more layers to stop the spread of COVID-19
Wear the mask over your nose and mouth and secure it under your chin
DO NOT

Put masks on someone two years and younger
Put masks on people who have trouble breathing, or people who cannot remove the mask without assistance
Wear masks intended for healthcare workers, for example, N95 respirators', 11, NULL);
INSERT INTO NEWS (TOPIC, THESIS, ADMIN_ID, NEWS_IMAGE) 
VALUES ('Situation Update for COVID-19', 'Overview
DO

Wear masks to help protect yourself from getting or spreading COVID-19
Wear masks with two or more layers to stop the spread of COVID-19
Wear the mask over your nose and mouth and secure it under your chin
DO NOT

Put masks on someone two years and younger
Put masks on people who have trouble breathing, or people who cannot remove the mask without assistance
Wear masks intended for healthcare workers, for example, N95 respirators', 13, NULL);
INSERT INTO NEWS (TOPIC, THESIS, ADMIN_ID, NEWS_IMAGE) 
VALUES ('SARS-CoV-2 Neutralizing Antibody LY-CoV555 in Outpatients with Covid-19', 'Overview
DO

Wear masks to help protect yourself from getting or spreading COVID-19
Wear masks with two or more layers to stop the spread of COVID-19
Wear the mask over your nose and mouth and secure it under your chin
DO NOT

Put masks on someone two years and younger
Put masks on people who have trouble breathing, or people who cannot remove the mask without assistance
Wear masks intended for healthcare workers, for example, N95 respirators', 12, NULL);
-- Import Data into table NEWS from file news (1).xlsx . Task successful and sent to worksheet.


SET DEFINE OFF
INSERT INTO ONLINE_CONSULTATION (CONSULTATION_ID, USER_UID, DOCTOR_ID, AGE, CONSULTATION_DATE, CLINICS, CITY, PHONE) 
VALUES (9001, 10039, 10034, 23, '19-Dec-20', 'SBS MED Clinic', 'Almaty', NULL);
INSERT INTO ONLINE_CONSULTATION (CONSULTATION_ID, USER_UID, DOCTOR_ID, AGE, CONSULTATION_DATE, CLINICS, CITY, PHONE) 
VALUES (9002, 10040, 10083, 24, '20-Dec-20', 'DASTAN Medical Centre', 'Shymkent', NULL);
INSERT INTO ONLINE_CONSULTATION (CONSULTATION_ID, USER_UID, DOCTOR_ID, AGE, CONSULTATION_DATE, CLINICS, CITY, PHONE) 
VALUES (9003, 10041, 10082, 36, '21-Dec-20', 'Regional Allergic Centre DIVERA', 'Karagandy', NULL);
INSERT INTO ONLINE_CONSULTATION (CONSULTATION_ID, USER_UID, DOCTOR_ID, AGE, CONSULTATION_DATE, CLINICS, CITY, PHONE) 
VALUES (9004, 10042, 10016, 40, '22-Dec-20', 'Pediatric center "CARUDO" in Zharokov', 'Almaty', NULL);
INSERT INTO ONLINE_CONSULTATION (CONSULTATION_ID, USER_UID, DOCTOR_ID, AGE, CONSULTATION_DATE, CLINICS, CITY, PHONE) 
VALUES (9005, 10043, 10054, 47, '23-Dec-20', 'SMART HEALTH UNIVERSITY CITY Medical Center', 'Almaty', NULL);
INSERT INTO ONLINE_CONSULTATION (CONSULTATION_ID, USER_UID, DOCTOR_ID, AGE, CONSULTATION_DATE, CLINICS, CITY, PHONE) 
VALUES (9006, 10044, 10080, 53, '24-Dec-20', 'Regional Allergic Centre DIVERA', 'Karagandy', NULL);
INSERT INTO ONLINE_CONSULTATION (CONSULTATION_ID, USER_UID, DOCTOR_ID, AGE, CONSULTATION_DATE, CLINICS, CITY, PHONE) 
VALUES (9007, 10045, 10083, 60, '25-Dec-20', 'DASTAN Medical Centre', 'Shymkent', NULL);
-- Import Data into table ONLINE_CONSULTATION from file online_consultations.xlsx . Task successful and sent to worksheet.

SET DEFINE OFF
INSERT INTO ONLINE_PCR (PCR_ID, CENTER_ID, USER_UID, CITY, PUNKT, PCR_DATE) 
VALUES (9008, 5002, 10046, 'Nur-Sultan', 'Medical Partners Korea Clinic LLP', '10-Jan-21');
INSERT INTO ONLINE_PCR (PCR_ID, CENTER_ID, USER_UID, CITY, PUNKT, PCR_DATE) 
VALUES (9009, 5017, 10047, 'Shymkent', 'MEDIKER network of medical centers', '11-Jan-21');
INSERT INTO ONLINE_PCR (PCR_ID, CENTER_ID, USER_UID, CITY, PUNKT, PCR_DATE) 
VALUES (9010, 5014, 10048, 'Karagandy', 'PCV "National Center of Expertise"', '12-Jan-21');
INSERT INTO ONLINE_PCR (PCR_ID, CENTER_ID, USER_UID, CITY, PUNKT, PCR_DATE) 
VALUES (9011, 5077, 10049, 'Almaty', 'PCV "National Center of Expertise"', '13-Jan-21');
INSERT INTO ONLINE_PCR (PCR_ID, CENTER_ID, USER_UID, CITY, PUNKT, PCR_DATE) 
VALUES (9012, 5004, 10050, 'Nur-Sultan', 'Invivo LLP', '14-Jan-21');
INSERT INTO ONLINE_PCR (PCR_ID, CENTER_ID, USER_UID, CITY, PUNKT, PCR_DATE) 
VALUES (9013, 5015, 10051, 'Karagandy', 'Invivo LLP', '15-Jan-21');
INSERT INTO ONLINE_PCR (PCR_ID, CENTER_ID, USER_UID, CITY, PUNKT, PCR_DATE) 
VALUES (9014, 5081, 10052, 'Shymkent', 'PCV "National Center of Expertise"', '16-Jan-21');
INSERT INTO ONLINE_PCR (PCR_ID, CENTER_ID, USER_UID, CITY, PUNKT, PCR_DATE) 
VALUES (9015, 5081, 10053, 'Shymkent', 'PCV "National Center of Expertise"', '17-Jan-21');
-- Import Data into table ONLINE_PCR from file online_pcr_zapis.xlsx . Task successful and sent to worksheet.


